version: '3.1'

services:
    ide:
        build: ./ide
        restart: always
        volumes:
            - ./sources:/root/project
        ports:
            - 8443:8443
        depends_on:
            - gitlab

    gitlab:
        build: ./gitlab
        restart: always
        ports:
            - 443:443
            - 80:80
            - 22:22
        volumes:
            - ./gitlab/data/config:/etc/gitlab
            - ./gitlab/data/logs:/var/log/gitlab
            - ./gitlab/data/data:/var/opt/gitlab

    sonarqube:
        build: ./sonarqube
        restart: always
        ports:
            - 9000:9000
        environment:
            - SONARQUBE_JDBC_USERNAME=changeme
            - SONARQUBE_JDBC_PASSWORD=changeme
        depends_on:
            - gitlab

    portainer:
      build: ./portainer
      restart: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./portainer/data:/data
      ports:
        - 9500:9000
      command: --admin-password $$2y$$05$$xpzJzEzLAxRX1m/6bvmIi.sEM8iE.sKUAimHG7b9B4pDjUkeB.QDG
      depends_on:
        - ide
        - gitlab
        - sonarqube

    nexus:
        build: ./nexus
        restart: always
        ports:
            - 8081:8081
