version: '3.1'

services:
    ide:
        build: ./ide
        restart: always
        volumes:
            - ./sources:/root/project
        ports:
            - 8443:8443

    gitlab:
        build: ./gitlab
        restart: always
        ports:
            - 443:443
            - 80:80
            - 22:22
        volumes:
            - ./gitlab/data/config:/etc/gitlab
            - ./gitlab/data/logs:/var/log/gitlab
            - ./gitlab/data/data:/var/opt/gitlab

    sonarqube:
        build: ./sonarqube
        restart: always
        ports:
            - 9000:9000
        environment:
            - SONARQUBE_JDBC_USERNAME=changeme
            - SONARQUBE_JDBC_PASSWORD=changeme
        volumes:
            - ./sources:/home/sources
