version: '3.1'

services:
    ide:
        build: ./ide
        restart: always
        volumes:
            - ./sources:/root/project
        ports:
            - 8443:8443
        depends_on:
            - gitlab
            - jenkins
            - sonarqube
            - nexus
            - registry
        networks:
            - docnet

    gitlab:
        build: ./gitlab
        restart: always
        ports:
            - 443:443
            - 80:80
            - 22:22
        volumes:
            - ./gitlab/data/logs:/var/log/gitlab
            - ./gitlab/data/data:/var/opt/gitlab
        networks:
            - docnet

    sonarqube:
        build: ./sonarqube
        restart: always
        ports:
            - 9000:9000
        environment:
            - SONARQUBE_JDBC_USERNAME=changeme
            - SONARQUBE_JDBC_PASSWORD=changeme
        depends_on:
            - gitlab
        networks:
            - docnet

    portainer:
        build: ./portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer/data:/data
        ports:
          - 9500:9000
        command: --admin-password $$2y$$05$$xpzJzEzLAxRX1m/6bvmIi.sEM8iE.sKUAimHG7b9B4pDjUkeB.QDG
        networks:
            - docnet

    nexus:
        build: ./nexus
        restart: always
        ports:
            - 8081:8081
        networks:
            - docnet

    registry:
        build: ./registry
        restart: always
        ports:
            - 5000:5000
        networks:
            - docnet

    jenkins:
        build: ./jenkins
        restart: always
        ports:
            - 8080:8080
            - 50000:50000
        networks:
            - docnet

networks:
    docnet:
